# Generated by Django 4.2.16 on 2024-10-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vchr_name', models.CharField(max_length=100)),
                ('txt_description', models.TextField()),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
