# Generated by Django 4.2.16 on 2024-10-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='int_status',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
